version: "3"

networks:
  default:
    external:
      name: sharelatex_overleaf

services:
  git_bridge:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: make run
    ports:
      - 8000:8000
